### ISSUE TITLE
Action add trait closing the game.

### ISSUE THREAD

**Issue by SparkleJ5** [Zerbu/Mod-Constructor-5#109]
I am trying to have a social interaction add a trait to actor sim -  the social interaction appears in the game but when it is performed the game crashes. I have not edited the files in s4s so code is all from the mod constructor. 
Better expectations also shows this in patch day scanner - _"SS_AutismMod_1GIT3FMTSI2 | Incorrectly matched tuning types found in tuning for trait_add in Instance: 3479457317 (SS_AutismMod_1GIT3FMTSI2), Types.ACTION. Expected 'E', got 'T'"_
Which seems to be an error in the XML created by mod constructor.

**Comment by ComMandaSims** [comment]
I’m having the same issue

**Comment by SparkleJ5** [comment]
Have either of you found a temporary fix to this issue?

**Comment by ComMandaSims** [comment]
I haven't yet.

**Comment by AlbertoJunior** [comment]
I have same problem with Gameplay Traits, the only one that works is Personality (CAS Selectable)

**Comment by mazlguy** [comment]
I have the same problem whit crashing when the trait is added but when I open and save the mod with version 10 then when the traits are added the game whont crash.

**Comment by SparkleJ5** [comment]
> I have the same problem whit crashing when the trait is added but when I open and save the mod with version 10 then when the traits are added the game whont crash.

Version 10 of what?

**Comment by mazlguy** [comment]
Sorry, Mod-Constructor V 5.10

**Comment by scipiogarling** [comment]
Maybe together we can narrow it down.  I have a career with seven branches, lots of traits as rewards. 
Adding any of the standard traits does NOT cause shutdown. Even hidden traits.
Adding a custom trait causes shutdown, but, NOT ALL custom traits.
It happens whether the trait is embedded within the career level or created as a separate element and then referred to by the Reward.
The crash does NOT happen if you are not playing the Sim.  You can add a custom trait to a non-active Sim/NPC.
When you try to either PLAY that Sim OR open that Sim in CAS, THEN it will cause a crash.
I have one custom trait that adds with no problem.  All it does is c;hange emotional impacts and decays.
Traits with either Broadcasters or Proximity features will cause a crash when added.
