### ISSUE TITLE
Buff Replacement Issues

### ISSUE THREAD

**Issue by MuvaSimmer** [Zerbu/Mod-Constructor-5#11]
### **BUFF REPLACEMENT ISSUES**

Hello! 

In testing out the beta version of MC5, a potential issue with **buff replacements**. I've realized that when making traits - _if you create buff replacements, when you test them out within game, they do not appear_. Instead, the original buff will continue to appear. 

Some examples of Instance ID's I've noticed this issue with:

- All Mourning / Grieving Buffs 
- 194622 (buff_Role_takecareofBaby)
- 76388 (Doomed Relationship (Buff_Jealousy_DoomedRelationship))

There are more instance ID's I've noticed this issue with as well but I wanted to make sure to report this first before listing anything further. Is there something we have to input to ensure our new buff replacements will override the base game buffs? 

Also, some of the instance id's in which have a 'hidden' buff will not appear at all if you create a buff replacement for them whereas in MC4, these buffs would appear with NO issue. For example, the instance ID: 12560 (buff_Pregnancy_NotShowing)

Hoping to Hear From You
Thank You For All Your Hard Work

![MC5 ISSUE](https://user-images.githubusercontent.com/98963987/152365575-41799270-28bb-4ed9-a9c2-a7c7acb3afed.JPG)
!

**Comment by Zerbu** [comment]
In my case, it appears to work fine, and there's no difference in the XML code between V4 and V5. Are you sure you remembered to give your Sim the trait? (That's something I sometimes forget to do)

**Comment by MuvaSimmer** [comment]
Hello!

Yes, I did. I also double checked and started the trait again from scratch.
As well as have a few other people test it out for me. Yet still the buffs
were not appearing.

Thank you for responding so quickly!

**Comment by Zerbu** [comment]
That sounds very strange then. Maybe you could post the .package file, and I can take a look for anything unusual.

**Comment by Zerbu** [comment]
Heads up: it's been 15 days since anyone has replied, so if someone doesn't reply soon, I'll be closing the issue.
