### ISSUE TITLE
Work From Home assignments expert improperly when using levels restrictions

### ISSUE THREAD

**Issue by ChrisPyre** [Zerbu/Mod-Constructor-5#119]
The exported XML for career track has the tuning ID for their objective in place of where the Career Track should be in the test for career level. This prevents wfh assignments with level restrictions from generating in game.

**Comment by scipiogarling** [comment]
Hm. That sounds like something we can fix by hand until the Constructor is updated to fix it (as tedious as that might be).

**Comment by scipiogarling** [comment]
Restrictions now work, but, as far as I can tell, Sims still only get $10 for working from home and doing a day of Working From Home prevents the Sim from returning to work.
