### ISSUE TITLE
5.13 still labels as 5.12

### ISSUE THREAD

**Issue by scipiogarling** [Zerbu/Mod-Constructor-5#126]
I am using the 5.13 version but it's still labeled as 5.12.  It's not an "old shortcut" issue: the 5.12 shortcut and folder have been deleted and all that's on my computer is the 5.13.

**Comment by jillsaintcyr** [comment]
I ran a Compare on 5.13 vs. 5.12 and it says there were no changes - looks like they both point to the same commit?

**Comment by mimacobaltini** [comment]
@Zerbu The tag 5.13 ([22a5668](https://github.com/Zerbu/Mod-Constructor-5/commit/22a5668f0f0fc02e268d7360032d345b73c7f634)) have the same commit code of the 5.12 ([22a5668](https://github.com/Zerbu/Mod-Constructor-5/commit/22a5668f0f0fc02e268d7360032d345b73c7f634)), as the same as master branch.
