### ISSUE TITLE
Some Unfixed Issues With Traits and Preferences

### ISSUE THREAD

**Issue by chingyu1023** [Zerbu/Mod-Constructor-5#128]
**Issues with traits:**
- Broken icons (when using a picker in gameplay mode) caused by n="icon" entered as n="trait_icon" in Trait Tuning.
- Unmatching between traits' tunings and its Simdata, e.g. species, tags are missing.
- Not generating display_name_gender_neutral when generating display_name, which causes trait names to appear blank in some context like the club filter if added. It would be grateful if we can give different display_name and display_name_gender_neutral.
- No picking of cas_trait_asm_param and conflicting_traits. I understand the conflicting_traits one can be tricky cuz it is meant to manually add the conflict for both sides of two conflicting traits. But picking cas_trait_asm_param can be really useful.

**Issues with preferences:**
- Likes and Dislikes are set as "Trait", not "Preference". It should be: c="Preference" i="trait" m="traits.preference" They appear fine in the game but it is still annoying to get the "preference_item" not for Trait warning in Error Notifier.
- No actual "trait conflict" is added in the trait tuning or sim data. This can be problematic if people add both likes and dislikes for one item with cheats in gameplay mode when Sims are not supposed to have both.
- Not generating display_name, display_name_gender_neutral, trait_description in the preferences' tuning. These only get generated in the SimData. This makes preferences not appear in trait pickers and appear as blank in the club filter if added.
- It would be handy if it auto-generates IDs for Likes and Dislikes from their label instead of the randomized ones and having to manually click that for all Likes and Dislikes.
- Again, broken icons (when using a picker in gameplay mode) caused by n="icon" entered as n="trait_icon"
- Again, selecting cas_trait_asm_param can be handy

Thank you for your work, Zerbu!

**Comment by jillsaintcyr** [comment]
Seconding this and watching - thank you! <3
