### ISSUE TITLE
Likes & Dislikes Have Empty SimData with v5 Beta 13

### ISSUE THREAD

**Issue by chingyu1023** [Zerbu/Mod-Constructor-5#130]
Big Issue: Likes & Dislikes (the trait tunings) exported with empty SimData with v5 Beta 13. This makes all exported preferences not appear in CAS.

**Comment by jillsaintcyr** [comment]
Confirming I see this issue as well. A fix would be most appreciated! 

I thought at first it was just happening when overriding the tuning ID, but realized it happens for any new preference trait regardless.
