### ISSUE TITLE
Categories not showing in game

### ISSUE THREAD

**Issue by zerbufan** [Zerbu/Mod-Constructor-5#154]
When attempting to add categories for my mods, they **don't seem to display anywhere within the game**. I've confirmed that **Python is installed correctly.**

This issue is hindering my modding work, as categorization is crucial for organization and user accessibility. I would appreciate your assistance in resolving this matter. If you need any additional information, please let me know.
![Capture](https://github.com/Zerbu/Mod-Constructor-5/assets/108773182/a70c030e-9c67-4e28-a1c1-e267faeebba4)

**Comment by Zerbu** [comment]
I know this post is old now, but if you're still having this issue: categories will only show if there's at least one preference assigned to them.
