### ISSUE TITLE
Can we make introductions?

### ISSUE THREAD

**Issue by CosmicZephyrus** [Zerbu/Mod-Constructor-5#16]
Hey there! I make custom traits and my traits all have their own new introduction interactions. Unless I am blind, I noticed while using V5 I can't make introduction interactions. I know this is beta so I am curious if it is a feature that just is not in yet or if there is a different process to make it solely an introduction.

**Comment by Zerbu** [comment]
It wasn't something I thought about while adding interactions, but since someone has requested it, I'll add it in the next update :)
