### ISSUE TITLE
Career: Sims can't go to work

### ISSUE THREAD

**Issue by scipiogarling** [Zerbu/Mod-Constructor-5#18]
I had no trouble constructing a straightforward custom career, packaging it, and putting it in game. But Sims in the career cannot go to work.  There is no "go to work" button, "go to work" is not one of their pie menu options, they get no calls to go to work.  I've looked at the package in Sims 4 Studio and can't see any reason why this would be this case; I'm stumped. File attached. Help will be appreciated.
[Scipio_OilBaron.zip](https://github.com/Zerbu/Mod-Constructor-5/files/8192843/Scipio_OilBaron.zip)
.

**Comment by scipiogarling** [comment]
yeah I have to go to work button now too, but still nothing. The Sim makes a slight glitchy movement as if to go, but resets and doesn't.  I even replaced the entire structure of the overall career tuning tab with one from a custom career that works fine (changing the code references where appropriate) but the same thing happens.  If the problem isn't there I don't know where else it could be and no one will even talk to me about it.

**Comment by BosseladyTV** [comment]
> yeah I have to go to work button now too, but still nothing. The Sim makes a slight glitchy movement as if to go, but resets and doesn't. I even replaced the entire structure of the overall career tuning tab with one from a custom career that works fine (changing the code references where appropriate) but the same thing happens. If the problem isn't there I don't know where else it could be and no one will even talk to me about it.

I haven't had time to troubleshoot it. Maybe this weekend. Question - Do you have a uniform for your career? I do and I'm wondering if that is the problem.

**Comment by scipiogarling** [comment]
I've tried it with and without uniform; no difference.
My questions about this have been up at various locations since before "Wedding Stories" dropped. :-(

**Comment by BosseladyTV** [comment]
Ok. Well another thing I've noticed is that when I made careers in MC4 I would always get a script file. But in MC5 I do not. That could be the problem. But I can't correct that problem.

**Comment by scipiogarling** [comment]
Now **that** is a useful clue. Is possible that the reason I can't see any wrong in the code is ... there's nothing wrong?  It just lacks a script file to support it? That would suggest...our Mod Constructors are not properly aligned with our Python programs to generate the proper script file...?

**Comment by BosseladyTV** [comment]
Oh yes! I didn't think about how it interacts with Python. So ... now what?

**Comment by scipiogarling** [comment]
We figure out who, either on-online or in our respective lives, can examine and help us unstick any connection difficulties between Mod Constructor and Python. Never having used either before this (I had to buy a PC for this project, I'm a Mac user), I'm not exactly savvy there.

**Comment by BosseladyTV** [comment]
I'm a Mac user too! so funny

**Comment by BosseladyTV** [comment]
If you discover anything, please pass along. And I'll do the same!

**Comment by scipiogarling** [comment]
Well, the answer here was that I had a too-recent version of Python installed and had to revert to an earlier one. That still didn't help MC5 communicate with it apparently, since it still doesn't generate a script file. But it DID allow me to install and begin to use MC4, which I wasn't able to before. My goal (being able to use a version of MC to make a career and the like) is accomplished; I am sorry if that doesn't help you accomplish yours of getting MC5 to work, however.

**Comment by QueenB-2579** [comment]
Hi have we found an answer to this issue? im having the same problem :/ i  created a career with the newest version from 3/20 v5.0-beta 3, all the notifications and the time frame are correct, but the Sim will not go to work, the bubble comes up and i have the "go to work" button but i get an error when its time to go, i still get the notifications that they are late and my boss calls, but they wont leave the house.

**Comment by FrenchieSim** [comment]
You can **solve** this by assigning balloons/speech bubbles in the **_Career Interaction category_**.  When going to work your Sim shows a balloon on top of their head, if you don't choose one, Sims can't go to work.

Also check you didn't give them "empty" assignments if it's a classic rabbithole career.

**Comment by scipiogarling** [comment]
Thanks, but actually, the problem that MC5 isn't generating a script file, and the career won't work with one.

**Comment by FrenchieSim** [comment]
Yes MC5 is slightly different, but I assure you custom careers can work this way, without an attached .ts4script. I'm playing with several careers I've made with MC5, no issue and no LE so far, everything is working like it's supposed to only with a .package file 😉

**Comment by scipiogarling** [comment]
Hm, interesting! So you are saying assign any sort of balloon set in career interaction category?
I didn't do anything (intentionally) about assignments. Do you mean gig assignments or work from home assignments or...?

**Comment by FrenchieSim** [comment]
@scipiogarling by default the work assignments are set to 2. I always put 0 if it's not a work-from-home career.

And yes if you choose any type of balloon in the Career Interaction category, your Sim should be able to go to work. Right now if you take a look at your mod file in MC5 you'll see "nothing" under balloon sub-category. Just browse and pick something and you're good to go! 😉

**Comment by EyeScreamCake** [comment]
Hey y'all, 
I'm unable to get a career to start later than 9am. I can get the duration to work, but not the start time. Are you all having that issue as well?

**Comment by scipiogarling** [comment]
I have not.

**Comment by BosseladyTV** [comment]
> Hey y'all, I'm unable to get a career to start later than 9am. I can get the duration to work, but not the start time. Are you all having that issue as well?

I am now!
I wasn't before, but I just made a new career, and it doesn't matter what time I put in for the start time, in game it only shows 9 am. I've cleared cache. And when I open the files in S4S it shows the time I entered, such as 7am, yet in game it still only shows 9am.

What is happening???

**Comment by BosseladyTV** [comment]
> @scipiogarling by default the work assignments are set to 2. I always put 0 if it's not a work-from-home career.
> 
> And yes if you choose any type of balloon in the Career Interaction category, your Sim should be able to go to work. Right now if you take a look at your mod file in MC5 you'll see "nothing" under balloon sub-category. Just browse and pick something and you're good to go! 😉

This worked for me. Thank you so much!
