### ISSUE TITLE
Indestructible buff

### ISSUE THREAD

**Issue by scipiogarling** [Zerbu/Mod-Constructor-5#19]
I've created what seems to be a pretty simple Fear buff and asked for it to expire in four hours and not persist.

The clock does r
[Scipio_scaredbuff_v2.zip](https://github.com/Zerbu/Mod-Constructor-5/files/8211424/Scipio_scaredbuff_v2.zip)
un out on it. But it persists.  I can't clear it out. Not even with a cheat.  I can't imagine how that's even possible.

**Comment by Zerbu** [comment]
Fixed in the new release: https://github.com/Zerbu/Mod-Constructor-5/releases
