### ISSUE TITLE
Exported mods

### ISSUE THREAD

**Issue by KiaraSims4Mods** [Zerbu/Mod-Constructor-5#2]
Hello,

I exported my mods folder to Mc5 but nothing appeared.

**Comment by Zerbu** [comment]
I assume you mean you exported a mod from MC5 but it didn't create a .package file? It seems odd that it's not working. I tested on a copy downloaded from here to make sure it wasn't just the way I uploaded, but it worked fine. Are there any features you used in your mod that might have caused it not to export?

**Comment by KiaraSims4Mods** [comment]
> 

Let me explain again sorry. I exported my mods folder from MC4 to MC5 to see if they would open with MC5.

**Comment by Zerbu** [comment]
The code of the two versions are very different, so it's not possible to load mods from MC4 in MC5, sorry.

I intend to keep updating MC4 for new patches as long as there are still a lot of mods that depend on it, but I won't be adding any new features.
