### ISSUE TITLE
Export error despite emotion category being unchecked

### ISSUE THREAD

**Issue by GaymerBorealis** [Zerbu/Mod-Constructor-5#20]
I'm using some custom moods for some moodlets and keep getting this export error:

"Add Emotion Category" doesn't support 15779804974680389382. No emotion category has been automatically added.
Element ID: 7LHXM8DI592
Element Name: Musical Stimuli
---

"Add Emotion Category" doesn't support 11975171252902949271. No emotion category has been automatically added.
Element ID: OY4V30F44Y2
Element Name: Ear Torture
---

This despite the fact that I've unchecked the "add to emotion category" setting on both buffs already :p

**Comment by Zerbu** [comment]
Fixed in the new release: https://github.com/Zerbu/Mod-Constructor-5/releases
