### ISSUE TITLE
"Reason Buff" Bug

### ISSUE THREAD

**Issue by Cosmiskie** [Zerbu/Mod-Constructor-5#21]
When I added a reason for the proximity buffs, it never showed up in the game like it was supposed to. The reasons always replaced itself with some random default EA trait name from CAS. But other than that, I really enjoy this Constructer and you made it so much easier to customize!

Thank you, Cosmiskie

**Comment by BosseladyTV** [comment]
Similar issue for me, but not on proximity buffs. Just general buffs on trait. Being replaced with (From Bro Trait) regardless of what I input in MC5.

**Comment by Zerbu** [comment]
Fixed in the new release: https://github.com/Zerbu/Mod-Constructor-5/releases
