### ISSUE TITLE
Error Exporting Python Scripts

### ISSUE THREAD

**Issue by NateTheL0ser** [Zerbu/Mod-Constructor-5#24]
I already have Python installed properly on my computer, and have repeatedly repaired my install, but every time I export a package, I get this error:

There was an error compiling the generated Python script. This can happen if you tried to install Python but the isntallation was interrupted. Please try running the installer again. It should be located in the "Python Installer" subfolder of where you extracted Mod Constructor.
Element ID: (No Element)
Element Name: (No Element)

**Comment by Zerbu** [comment]
I've fixed multiple Python issues since this post was created, so I'm closing it as it's old. If anyone is still having problems with exporting Python scripts, feel free to create a new post.
