### ISSUE TITLE
Social Interactions and Buffs (Question)

### ISSUE THREAD

**Issue by Delroyy** [Zerbu/Mod-Constructor-5#25]
I've been using your mod constructer v5 for a few weeks. The issue I've been trying to figure out lately is how to make my Custom Social Interaction trigger a buff for the other sims(target sim) after interacting. Do i use broadcaster for that matter?

**Comment by CosmicZephyrus** [comment]
Hey! I **_think_** I can help you out! So to understand, you want the Target sim to get a buff after your sim (actor) performs the interaction on them correct? If so then follow along! If not then just disregard this whole thing! 

1) Obviously open the constructor. 

2) Select/Create your social interaction you want to add buffs to. I assume you know how. Under "Main Content" move over to "Actions" and click "create". If you want your actor AND target sim to have a buff click it TWICE. If you just want the target sim only once will suffice! 

![image](https://user-images.githubusercontent.com/100459577/160262557-61a007fc-2e9b-470c-ab50-19ac7a294c09.png)

3) Select "New Loot Action". 

4) Under "New Loot Action" we see check marks. The first 2 are what I call positive outcomes. The last 3 are what I call negative outcomes. With the first two checked, we can create our first positive buff. Click "Add Condition Group" Right click on the "Always Run" click "add action". To the right select the gear and choose "Buffs: Add Buff" then finally click the "+" to the right.

![image](https://user-images.githubusercontent.com/100459577/160262738-c6921557-b544-442e-8ef5-dceb430f1696.png)

5) Write out your buff how you want as if it will be placed on the target sim! I use a positive and negative system you can do what you please! You can check all the boxes and this buff will occur no matter the outcome. If this is redundant I apologize I don't want to leave something out incase you don't know or anyone else! Guides are short to none on v5. 

![image](https://user-images.githubusercontent.com/100459577/160262911-28c4166d-bdf3-435a-adad-3020e2657dc0.png)

6) If you have not, at the bottom box that says "Participant" write in exactly as I have here: TargetSim

7) Finish your interaction by adding in as many buffs you want. In this case I did one TargetSim and one Actor buff. For the actor  buff, same process but write the buff as if it is applied to YOUR sim.  And in the bottom box, write: Actor 

8) Once done, move to "Conditions" which is under Main Content. We will keep it simple. Click "Add Condition". Select gear to the right. You can make interactions behave in many ways. But for now just select "Sim Info Condition" unless you know how to use something else feel free to! Just uncheck the life stages you DO NOT want to use the interaction. And you can mess with Gender, NPC etc if you wish! 

9) Now just export and name accordingly! Launch your game and test! Have two sims in your household have one use the interaction on the other and look in the TargetSim's buffs. You should see it! 

![image](https://user-images.githubusercontent.com/100459577/160263170-63bf2266-ff5f-4df3-9f1d-b401ab29f25f.png)


I hope this all makes any sense! Maybe you figured it out by now, but nonetheless, this is still  good to have incase anyone else is wondering!

**Comment by CosmicZephyrus** [comment]
> I've been using your mod constructer v5 for a few weeks. The issue I've been trying to figure out lately is how to make my Custom Social Interaction trigger a buff for the other sims(target sim) after interacting. Do i use broadcaster for that matter?





Hey! I think I can help you out! So to understand, you want the Target sim to get a buff after your sim (actor) performs the interaction on them correct? If so then follow along! If not then just disregard this whole thing!

1) Obviously open the constructor.

2) Select/Create your social interaction you want to add buffs to. I assume you know how. Under "Main Content" move over to "Actions" and click "create". If you want your actor AND target sim to have a buff click it TWICE. If you just want the target sim only once will suffice!



3) Select "New Loot Action".

4) Under "New Loot Action" we see check marks. The first 2 are what I call positive outcomes. The last 3 are what I call negative outcomes. With the first two checked, we can create our first positive buff. Click "Add Condition Group" Right click on the "Always Run" click "add action". To the right select the gear and choose "Buffs: Add Buff" then finally click the "+" to the right.



5) Write out your buff how you want as if it will be placed on the target sim! I use a positive and negative system you can do what you please! You can check all the boxes and this buff will occur no matter the outcome. If this is redundant I apologize I don't want to leave something out incase you don't know or anyone else! Guides are short to none on v5.

![image](https://user-images.githubusercontent.com/100459577/160263483-b0ce23ce-9467-421b-9e33-b5d757f1fd96.png)


6) If you have not, at the bottom box that says "Participant" write in exactly as I have here: TargetSim

7) Finish your interaction by adding in as many buffs you want. In this case I did one TargetSim and one Actor buff. For the actor buff, same process but write the buff as if it is applied to YOUR sim. And in the bottom box, write: Actor

8) Once done, move to "Conditions" which is under Main Content. We will keep it simple. Click "Add Condition". Select gear to the right. You can make interactions behave in many ways. But for now just select "Sim Info Condition" unless you know how to use something else feel free to! Just uncheck the life stages you DO NOT want to use the interaction. And you can mess with Gender, NPC etc if you wish!

![image](https://user-images.githubusercontent.com/100459577/160263506-cfbd6a58-19c0-4887-a3d3-0ca399ceb9b1.png)


9) Now just export and name accordingly! Launch your game and test! Have two sims in your household have one use the interaction on the other and look in the TargetSim's buffs. You should see it!

![image](https://user-images.githubusercontent.com/100459577/160263448-b7f96765-0def-4867-9438-541952e4fa95.png)


I hope this all makes any sense! Maybe you figured it out by now, but nonetheless, this is still good to have incase anyone else is wondering!

**Comment by Delroyy** [comment]
> > I've been using your mod constructer v5 for a few weeks. The issue I've been trying to figure out lately is how to make my Custom Social Interaction trigger a buff for the other sims(target sim) after interacting. Do i use broadcaster for that matter?
> 
> Hey! I think I can help you out! So to understand, you want the Target sim to get a buff after your sim (actor) performs the interaction on them correct? If so then follow along! If not then just disregard this whole thing!
> 
> 1. Obviously open the constructor.
> 2. Select/Create your social interaction you want to add buffs to. I assume you know how. Under "Main Content" move over to "Actions" and click "create". If you want your actor AND target sim to have a buff click it TWICE. If you just want the target sim only once will suffice!
> 3. Select "New Loot Action".
> 4. Under "New Loot Action" we see check marks. The first 2 are what I call positive outcomes. The last 3 are what I call negative outcomes. With the first two checked, we can create our first positive buff. Click "Add Condition Group" Right click on the "Always Run" click "add action". To the right select the gear and choose "Buffs: Add Buff" then finally click the "+" to the right.
> 5. Write out your buff how you want as if it will be placed on the target sim! I use a positive and negative system you can do what you please! You can check all the boxes and this buff will occur no matter the outcome. If this is redundant I apologize I don't want to leave something out incase you don't know or anyone else! Guides are short to none on v5.
> 
> ![image](https://user-images.githubusercontent.com/100459577/160263483-b0ce23ce-9467-421b-9e33-b5d757f1fd96.png)
> 
> 6. If you have not, at the bottom box that says "Participant" write in exactly as I have here: TargetSim
> 7. Finish your interaction by adding in as many buffs you want. In this case I did one TargetSim and one Actor buff. For the actor buff, same process but write the buff as if it is applied to YOUR sim. And in the bottom box, write: Actor
> 8. Once done, move to "Conditions" which is under Main Content. We will keep it simple. Click "Add Condition". Select gear to the right. You can make interactions behave in many ways. But for now just select "Sim Info Condition" unless you know how to use something else feel free to! Just uncheck the life stages you DO NOT want to use the interaction. And you can mess with Gender, NPC etc if you wish!
> 
> ![image](https://user-images.githubusercontent.com/100459577/160263506-cfbd6a58-19c0-4887-a3d3-0ca399ceb9b1.png)
> 
> 9. Now just export and name accordingly! Launch your game and test! Have two sims in your household have one use the interaction on the other and look in the TargetSim's buffs. You should see it!
> 
> ![image](https://user-images.githubusercontent.com/100459577/160263448-b7f96765-0def-4867-9438-541952e4fa95.png)
> 
> I hope this all makes any sense! Maybe you figured it out by now, but nonetheless, this is still good to have incase anyone else is wondering!

Yes, Thank you so much for your help!

**Comment by CosmicZephyrus** [comment]
> Yes, Thank you so much for your help!

of course! If you have any questions, don't hesitate to ask!

**Comment by scipiogarling** [comment]
Can I add a related question, CZ?  I'm making a Trait in MC5. Any time I add Actions to a Social Interaction for the Trait, the Interaction fails to run, even where those actions are game reference loots.  Clearly, it's designed so that you can add Actions because it's one of the tabs; but why don't the Interactions run when I do so?
