### ISSUE TITLE
Support for macOS devices

### ISSUE THREAD

**Issue by ProfessorConfundus** [Zerbu/Mod-Constructor-5#26]
Hi!
I've recently discovered this seemingly wonderful modding tool, and it looks like it would be great to use, but I have a problem: 
This tool doesn't have a macOS build (afaik), so I was wondering, is there a big reason that would make this very difficult to implement, or is it simply just that it would be harder to test? If the latter, I'm sure myself and many other Mac users in the Sims modding community would be willing to contribute and test to iron out any problems!

**Comment by Zerbu** [comment]
While I would like to support Mac, it's not simple to do. It would basically mean recreating the entire program for the ground up for Mac. It's not really feasible :(
