### ISSUE TITLE
Social interactions from custom trait not working

### ISSUE THREAD

**Issue by andizzlethesimma** [Zerbu/Mod-Constructor-5#27]
I'm new to modding, but after following a couple of tutorials, the program seemed pretty easy to work with, and I was very proud of my first trait! However, when I put it in-game for testing, the social interactions would not go through. I could click them, and my sims would get ready to fulfill them. However, right before the interaction started, my sims would immediately reset (the performer sim and the target sim). Can I get any help on how to fix this? Or maybe I just need a current tutorial to follow. Please help!

**Comment by soyuzcat** [comment]
Have you added balloons to the interaction?

**Comment by scipiogarling** [comment]
I have this exact problem and, yes, I have added balloons.

**Comment by Libror** [comment]
Same problem right here. Nothing showing up.
