### ISSUE TITLE
No scrollbar

### ISSUE THREAD

**Issue by TiredGamer71** [Zerbu/Mod-Constructor-5#29]
When I tried to create a mod, the full HD display was too small. There was no possibilities to scroll down, because no scrollbar.
![ModCreator-5-bug](https://user-images.githubusercontent.com/104513413/165547729-aa93d7b8-eb36-40ee-9ddb-490fe71db55f.jpg)

When I tried to set up a few multipliers, V5 only accepted integers, the V4 didn't work that way.
![ModCreator-5-bug-2-V4reference](https://user-images.githubusercontent.com/104513413/165549567-c61ee858-20a1-459e-a749-f04013d37246.jpg)
![ModCreator-5-bug-2](https://user-images.githubusercontent.com/104513413/165549577-e94ba610-8716-4d60-92a3-e4a3edd83cd7.jpg)
.

**Comment by Zerbu** [comment]
The first issue has been fixed in the latest update: https://github.com/Zerbu/Mod-Constructor-5/releases
I don't know what would be causing the second problem though, since I don't have the same problem. Does it effect the slider, the input box, or both? Does it still happen when you try to enter the value manually?

**Comment by TiredGamer71** [comment]
Both. And the whole thing is a pretty wierd.
When I changed the value with the scrollbar, only integer was visible.
When I wrote a non-integer value:
1.5 <enter> --> 1
1,5 <enter> --> 15 (in my country, the "," is the default.)
1.5 <arrow up button> --> gray, but usable --> 1
1,5 <arrow up button> --> 151 <arrow up button again> --> 1511 <arrow up button again> --> 1512

1.5 <arrow down button> --> gray, but usable --> 1
1,5 <arrow down button> --> 149 <arrow down button again> --> 1489 <arrow down button again> --> 14889 <arrow down button again> --> 148889
