### ISSUE TITLE
Custom Image Error

### ISSUE THREAD

**Issue by marielynette** [Zerbu/Mod-Constructor-5#3]
Whenever trying to import a custom image, I get this error:

Unable to load DLL 'squishinterface_x64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

However, upon reopening the icon selection, the custom image I tried to import will be there, but will not have exported into the package file. Instead, there is an empty DST file. 
![MCV5 custom image error](https://user-images.githubusercontent.com/97465974/148807284-f94c3b72-59b3-428c-82af-83950bddb5b0.png)

**Comment by Zerbu** [comment]
Thanks for the report! This is because a DLL was missing from the release build, and I didn't catch it initially because it was there in the debug build. The issue has been fixed in v5.0.alpha-3
https://github.com/Zerbu/Mod-Constructor-5/releases/tag/v5.0-alpha.3
