### ISSUE TITLE
Custom Trait Picker

### ISSUE THREAD

**Issue by sesesimmi** [Zerbu/Mod-Constructor-5#35]
Hi Can Anyone Help with fixing this issue?
![Screenshot 2022-05-19 204236](https://user-images.githubusercontent.com/104830440/169431906-5e90d5fe-9e91-4e78-a34e-f535cbd04b60.png)

**Comment by bigbangzlzl** [comment]
It should be related to the feature. I tried to build the feature in MCV4, associated with the feature manager in MCV5, and it shows the picture

**Comment by Zerbu** [comment]
This sometimes shows up instead of the llama icon for traits that don't have any icons set. If you set the icons, it should work properly.
