### ISSUE TITLE
Triggering loot?

### ISSUE THREAD

**Issue by tant-ryschpysch** [Zerbu/Mod-Constructor-5#36]
Is there something new to keep in mind when making loots in v5? I have made test loots, that trigger notifications, but they don't show up... How do I trigger the loots? They are set to "always run", and I never had this problem in v4. Is there something obvious I'm missing?

**Comment by nabrappy** [comment]
i found this yesterday while trying to look up my own issues, hopefully it helps you! i am not familiar with loots yet myself

"...To trigger the loots, one thing I usually do is create an interaction to make them run. The always run option tells the action to always run if conditions are met, but to make it actually run, you can create an immediate interaction, social interaction, or mixer interaction. I will make a note to cover this in an upcoming video."
source: https://www.youtube.com/watch?v=5krrf-rSNe8&ab_channel=SimsModelSimmer
