### ISSUE TITLE
Is it possible to change the interface language?

### ISSUE THREAD

**Issue by Burinis** [Zerbu/Mod-Constructor-5#37]
Hello! I would like to ask if this program has been translated into Russian? I'm just from Russia, my English is not very good. I also noticed that in the folder with the program, among other things, there is a folder "ru" (Russian). Is this the translation of the interface? And how to change the language?

**Comment by Zerbu** [comment]
There are plants to add the option to translate the program, but it won't be available until it fully leaves beta, since text strings are changing way too often at the current time.
