### ISSUE TITLE
Exporting Error

### ISSUE THREAD

**Issue by marielynette** [Zerbu/Mod-Constructor-5#4]
If I export a mod, it works just fine. If I then try to export again and override the previous export file  (whether i've made changes or not), constructor tells me:

The process cannot access the file 'C:\Users\marie\Desktop\MC5 V3\Projects\marlynsims_GoldDigger\Imports\00B2D882!0!93C217B415E106DB.dds' because it is being used by another process.

Even if the file is not open anywhere else. I have to shut down Constructor, and re-open for it to be able to export again and override the file. 

Edit: I've also realised that it also does it even if I am trying to export it as a new file, and not just override an older file. 

![mc error](https://user-images.githubusercontent.com/97465974/148920112-ad03945d-4a9f-4eb9-b3ff-32d9b6f5a420.png)

**Comment by Zerbu** [comment]
Thanks for the report, it has been fixed in the new release! https://github.com/Zerbu/Mod-Constructor-5/releases
