### ISSUE TITLE
Social Interactions

### ISSUE THREAD

**Issue by EunolaSims4** [Zerbu/Mod-Constructor-5#40]
I just had a quest on if I was creating my social interactions correctly. If I want both the Actor dim and the TargetSim to get buffs from the interaction do I make two "Always Run" condition groups both with an action of adding a buff but one for Actor and the other for TargetSim

**Comment by Zerbu** [comment]
You'll have to create two actions if you want both the actor and the target to receive the buff. You don't have to create two condition groups though, you can put both actions in the same one.
