### ISSUE TITLE
How to link my scripts with custome phone tabs and labels?

### ISSUE THREAD

**Issue by NataliaAssange** [Zerbu/Mod-Constructor-5#43]
Hi Zerbu,
I have made the main part of stock market mod in M4. You can see in my repository, it's very simple and contains only 3 functions: check(), buy(), and sell(), and I have also created a new phone tab and labels (like WonderfulWhims, if you have that). Now I want to link my scripts with my phone. For example, in the following picture, I want to click "buy" on my phone and run the function buy(). Also, I want to click the stock market tab (the arrow icon) and run the function check(). What should I do?
![Screenshot 2022-06-24 153741](https://user-images.githubusercontent.com/36265870/175487154-ae2a960a-762e-42bf-8f5f-8e5a7831ae0a.png)
Thank you very much and looking forward to your reply!

BR
Natalia

**Comment by k80hull** [comment]
Hi Natalia, you’re probably best asking in Zerbus Discord as this is for issues with MC5. Your mod looks great!

**Comment by NataliaAssange** [comment]
Maybe my poor English and poor understanding of coding make you confused.
I want to ask: if I make a new tab in the phone with MC5, where can I see the python scripts it creates? I know how to run a function when clicking on a button.
