### ISSUE TITLE
trouble finding certain features [active/semi-active career etc]

### ISSUE THREAD

**Issue by nabrappy** [Zerbu/Mod-Constructor-5#46]
i was hoping to get some more information on the constructor and how it works to create careers.

which settings are designated for making the career active or semi-active? i cannot seem to figure it out. 
i was also having trouble figuring out what "bounds" and "level restrictions" mean in relation to settings called "lower" and "upper" bounds. 
and i wanted to know if it's possible to create a promotion requirement along the lines of a sim needing to level a skill to a specific level to progress in the career, and how to make work from home assignments occur - i have them set but they don't trigger (probably because i'm missing something on how to get them working).

if there happens to be a tutorial or a guide for V5 somewhere i wouldn't mind using it in the future, i did try to google and try things myself first before asking with no luck for these specific questions. 
thanks in advance for any help or tips. 

(aside from that i did want to mention i am also having the issue where when exporting there is no script file, as someone else had reported)

**Comment by Zerbu** [comment]
Mod Constructor doesn't currently have the ability to make fully active careers, but you can make semi-active ones by adding "Work from Home Assignments". Level restrictions mean that you'll only get the assignment at a certain level between the lower and upper bound. If your Sim isn't getting any assignments, you might have already set the bounds too high.
Promotion requirements are defined in the "Promotion Objective Set" tab.
