### ISSUE TITLE
Adding image to Career gives error

### ISSUE THREAD

**Issue by xosdr** [Zerbu/Mod-Constructor-5#48]
When I try adding an image for career, from a screenshot from the Sims 4 game. I keep getting this error. It doesn't show up all the time but on some images it does and others it don't.

![Schermafbeelding 2022-08-02 090402](https://user-images.githubusercontent.com/100002162/182246358-b7868c93-c856-4877-979b-24af877a0b8e.png)

**Comment by Zerbu** [comment]
This is a problem with DDSPanel, the library used for converting PNG files to DDS, failing to convert images with certain dimensions. It's not something I can fix, but the next update should show a less vague error message. You can avoid the issue by resizing the image to a power of 2 number like 512x512.
