### ISSUE TITLE
Possible bug?? 

### ISSUE THREAD

**Issue by Kittytailzz** [Zerbu/Mod-Constructor-5#5]
I have never made my own mod before so I am unsure if this is a me problem or an actual bug. I get this error when I try and export my trait
![Y THO](https://user-images.githubusercontent.com/97680752/149343519-9d87f2a4-c884-4239-b54e-cc8af35fe15a.PNG)

**Comment by Zerbu** [comment]
Yep, looks like a bug.

Which particular features does your mod use? I can tell from the screenshot it uses a Compound Condition, but which particular conditions does it use within the Compound Condition? And which particular loot actions does it use?

**Comment by Kittytailzz** [comment]
ok so i have screen shot for most of the compound conditions. 
![example 1](https://user-images.githubusercontent.com/97680752/149425370-2e10c2c4-6fe0-4033-8b96-8e95582e429a.PNG)
for the above the compound condition I have a statistic condition and another compound condition as an "and" this second compound condition is made of 20 "0r" groups made of a skill condition and a buff condition (its related to likes/dislikes so i think i need to change that to trait condition that might be the problem)
![example2](https://user-images.githubusercontent.com/97680752/149427020-5fbbdf9b-56e6-4747-9e60-5d262feb252b.PNG)
above are the actions used they are a custom buff and some statistic changes
![example3](https://user-images.githubusercontent.com/97680752/149427201-08b758d1-bf14-4403-8916-b78bbcaf05ad.PNG)
 above is the second action set its almost the exact same except the likes/dislikes are reversed and the action is a different buff and only one stat is being changed
![example 5](https://user-images.githubusercontent.com/97680752/149427368-e7a76c2d-adc6-431c-933a-58aef0e4ad32.PNG)
above is the last actin set this one im not too sure about basically using an emotion condition with statistic conditions to try and apply a buff after the custom buff from the first action set has disappeared. this was supposed to be a simple trait but i may have gotten carried away.

**Comment by Zerbu** [comment]
I tried to reproduce what is shown in the screenshot, but couldn't get the same error you have. Is there any chance you could send the contents of the mod as a .zip file? (The files should be located in the "Projects" subfolder of the folder you extracted the program to)

**Comment by Kittytailzz** [comment]
AH! Its been fixed, first, I realized I had not updated to alpha.5, so I did that, I believe my old alpha folder was exported incorrectly. Either way it works, sorry for wasting your time!

**Comment by Zerbu** [comment]
Good to see you have it resolve at least!

And good luck with your mod. I don't know exactly what it is you're trying to do, but a simpler way to do what you seem to be trying to do is to use the "I Like <Skill>" buffs (the ones that appear _while_ a Sim is performing an interaction they like). You can check for all of them in one buff condition, and you don't need a Skill In Use condition because the Sim would have to already like the activity for those buffs to appear in the first place.

**Comment by DaleRuneMTS** [comment]
> a simpler way to do what you seem to be trying to do is to use the "I Like [Activity]" buffs (the ones that appear _while_ a Sim is performing an interaction they like). **You can check for all of them in one buff condition**

Wait, you can do that? :O

**Comment by Zerbu** [comment]
Yeah, just add them all to the whitelist. The Sim is only required to have one buff from the whitelist, not all of them.
