### ISSUE TITLE
Problem with export Pie Menu Categories in Social Interaction

### ISSUE THREAD

**Issue by Sorias01** [Zerbu/Mod-Constructor-5#55]
I am using the Beta .6 Version

If i change the pie menu category in the "Social Interaction" Element then the change will be ignored while exporting the Package.
I was looking in the xml of the exported interaction and it was still the default ID for the interaction type.

![examble](https://user-images.githubusercontent.com/116228077/196816425-a18d5763-6d4b-4b2a-9fe3-4a127ced121e.png)

**Comment by Sorias01** [comment]
I forgot, it was tested with mischief and mean interactions.
I tryed it with default categories, self made categories and with the manual input.
It was with all the same.

**Comment by Zerbu** [comment]
Thanks for the report! This will be fixed in the next update.
(The "category" actually isn't supposed to be in the TuningActions file at all, since it's defined in code)
