### ISSUE TITLE
Is there a way to trigger an action/event every days or by a set timer?

### ISSUE THREAD

**Issue by SmokingDuckk** [Zerbu/Mod-Constructor-5#56]
Hello, i'm still looking on if it's possible to trigger an action/event every sims day or by a set timer. Like for exemple you get a house fire every 10 ig hours. If anyone could help me thank you!

Also, i'm sorry that this isn't an actual issue.

**Comment by Zerbu** [comment]
This sounds a bit complex for Mod Constructor, and is more in the realm of Python scripting. Thanks for the suggestion though!
