### ISSUE TITLE
Buff/Trait Condition Confusion

### ISSUE THREAD

**Issue by DaleRuneMTS** [Zerbu/Mod-Constructor-5#8]
I'm currently attempting to add a buff condition for a social interaction (as in, a social interaction only appears when a certain buff is present), but the buff condition whitelist and blacklist sections erroneously pull up traits, rather than buffs. Is this a deliberate thing, seeing as core buffs are part of traits as well, or a genuine oversight?

![traitbug](https://user-images.githubusercontent.com/97731005/149493306-6990551d-773f-40ae-b128-e90f80cf961d.png)

**Comment by Zerbu** [comment]
It's a bug, thanks for the report. It should be fixed in the next update (which will hopefully be released later today).
