### ISSUE TITLE
replacing the animations with own Blender files

### ISSUE THREAD

**Issue by JakobBlue** [Zerbu/Mod-Constructor-5#89]
I would like to replace the animations ( success, success (target), failure, failure (target)) with my own edited animations. Is there a way to set it in the Mod Constructor (like picture 1)?

picture 1:<img width="584" alt="picture 1" src="https://user-images.githubusercontent.com/125775207/219906531-9dcb11cf-1261-446b-8aa5-281418335c73.png">

 in the case of building any sentence incorrectly, I apologize for language mistakes, my native language is German

**Comment by ChrisPyre** [comment]
This requires software outside of Mod Constructor, and can be pretty complex. You'll need Sims 4 Studio and import the blender files as clips. You'll then need to create an animation state machine, and an animation XML in sims 4 studio. It's fairly complicated. Eventually you can add these animations to your interactions by pasting the animation instance ID into the manual input slot

**Comment by JakobBlue** [comment]
Thank you @ChrisPyre 
I think your explanation is helping me. The only explanation about the Animation State Machine structure that I could find is this tutorial: 
https://sims4studio.com/thread/20149/creating-animated-objects-interaction-tutorial
but its not helping. 

I have imported my Blender files into a pose pack and got now my clip and clip header so I have probably the clips done you wrote about. 
The only solution I can see based on browsing over the ASM is changing the SourceFile- and IkConfiguration-Tags, right? The problem I have, I don't know where to start and what the steps are to connect my clips to the ASM.

> Eventually you can add these animations to your interactions by pasting the animation instance ID into the manual input slot

And with your last sentenece, do you mean the Animation State Machine Instance or the Animation Tuning Resource Instance?
If so the Animation Tuning Resource, I assume to change the p-Value and its T-Tag-Value to something of the in the future finished ASM.

@ChrisPyre  Do you have an idea what I can try next for finishing the Animation State Machine?

**Comment by ChrisPyre** [comment]
So from my own experience sourcefile and ik configuration tags actually seem to not do anything. what you want to look for is the clip controller underneath each state, where you can input the names of your new clips, replacing the name of EA's og clips.
You then want to create an animation tuning file which has the instance id for your ASM and the starting state. the instance id from that Animation tuning is what you plug in to mod constructor.

**Comment by JakobBlue** [comment]
Thank you so much for the help.
It finally worked after a bit of work. You were probably right with your last sentence, but I got the solution with the **TuningID** instead. 

This is the result with a simple animation:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/125775207/220766968-1772dd68-5dc3-443c-931f-00ce358e2f87.gif)
