### ISSUE TITLE
Global traits?

### ISSUE THREAD

**Issue by AmkiTakk** [Zerbu/Mod-Constructor-5#93]
Mod Constructor 4 had the option to make global traits, which was especially useful to alter skill gain speed, among other things. However, I can't seem to find a way to make a trait global in version 5, is it not available yet, or has it been renamed?

Any help is greatly appreciated.

**Comment by lealinucs** [comment]
Go to "Special case" in the left menu of your trait. you will find the option at the bottom.

**Comment by AmkiTakk** [comment]
Found it, thank you very much!
